# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

  deploy_staging:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing project dependencies
          command: yarn install

      - run:
          name: Generating a production build
          command: yarn build

      - save_cache:
          paths:
            - node_modules
            - functions/node_modules

          key: v1-dependencies-{{ checksum "package.json" }}

      - deploy:
          command: |
            node_modules/.bin/firebase deploy --project ${STAGING_PROJECT_ID} --token ${FIREBASE_TOKEN}

  deploy_production:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing project dependencies
          command: yarn install

      - run:
          name: Generating a production build
          command: yarn build

      - save_cache:
          paths:
            - node_modules
            - functions/node_modules

          key: v1-dependencies-{{ checksum "package.json" }}

      - deploy:
          command: |
            node_modules/.bin/firebase deploy --project ${PRODUCTION_PROJECT_ID} --token ${FIREBASE_TOKEN}

  deploy_storybook:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing project dependencies
          command: yarn install

      - run:
          name: Generating a production build
          command: yarn build-storybook

      - save_cache:
          paths:
            - node_modules
            - functions/node_modules

          key: v1-dependencies-{{ checksum "package.json" }}

      - deploy:
          command: |
            node_modules/.bin/firebase deploy --project ${STORYBOOK_PROJECT_ID} --token ${FIREBASE_TOKEN}

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build

      - deploy_staging:
          requires: 
            - build

          filters:
            branches:
              only: master

      - deploy_storybook:
          requires: 
            - build

          filters:
            branches:
              only: master

      - deploy_production:
          requires:
            - build

          filters:
            branches:
              only: production
